apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: ci-test
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
